/**
 * AWS Configuration for Admin Dashboard
 * 
 * Configuration is loaded from /config.json (auto-generated by CDK FrontendStack)
 * The config.json file is created during CDK deploy and uploaded to S3
 */

interface AppConfig {
  region: string;
  cognitoUserPoolId: string;
  cognitoClientId: string;
  cognitoDomain: string;
  cloudFrontUrl: string;
  apiEndpoint: string;
  syncApiEndpoint?: string;
  demoMode?: boolean;
}

// Runtime config loaded from /config.json
let runtimeConfig: AppConfig | null = null;

/**
 * Load config from /config.json at runtime
 * This file is auto-generated by CDK FrontendStack during deployment
 */
export const loadConfig = async (): Promise<void> => {
  try {
    const response = await fetch('/config.json', {
      cache: 'no-cache' // Always get fresh config
    });
    if (response.ok) {
      runtimeConfig = await response.json();
      console.log(' Loaded config from /config.json');
    } else {
      console.error(' Failed to load /config.json:', response.status);
    }
  } catch (error) {
    console.error(' Could not load /config.json:', error);
  }
};

// Helper to get config value
const getConfig = <K extends keyof AppConfig>(key: K): AppConfig[K] | undefined => {
  return runtimeConfig?.[key];
};

export const config = {
  // AWS Region
  get region(): string {
    return getConfig('region') || 'ap-southeast-1';
  },
  
  // Cognito Configuration
  get cognitoUserPoolId(): string {
    return getConfig('cognitoUserPoolId') || '';
  },
  get cognitoClientId(): string {
    return getConfig('cognitoClientId') || '';
  },
  get cognitoDomain(): string {
    return getConfig('cognitoDomain') || '';
  },
  
  // API Gateway Configuration
  get api() {
    return {
      endpoint: getConfig('apiEndpoint') || '',
      adminPath: '/admin',
      crawlerPath: '/crawler',
    };
  },
  
  // Consultant Sync API (outside VPC)
  get syncApiEndpoint(): string {
    return getConfig('syncApiEndpoint') || '';
  },
  
  // OAuth URLs (derived from cloudFrontUrl)
  get redirectSignIn(): string {
    const baseUrl = getConfig('cloudFrontUrl') || 'http://localhost:5173';
    return baseUrl.endsWith('/callback') ? baseUrl : `${baseUrl}/callback`;
  },
  get redirectSignOut(): string {
    return getConfig('cloudFrontUrl') || 'http://localhost:5173';
  },
  
  // Demo Mode (for local development without AWS)
  get demoMode(): boolean {
    return getConfig('demoMode') || false;
  },
};

/**
 * Validate that required configuration is loaded
 */
export const validateConfig = (): boolean => {
  if (!runtimeConfig) {
    console.error(' Config not loaded. Call loadConfig() first.');
    return false;
  }
  
  const requiredFields: (keyof AppConfig)[] = [
    'cognitoUserPoolId',
    'cognitoClientId', 
    'cognitoDomain',
    'apiEndpoint'
  ];
  
  const missingFields = requiredFields.filter(field => !runtimeConfig?.[field]);
  
  if (missingFields.length > 0 && !config.demoMode) {
    console.error(' Missing required config fields:', missingFields.join(', '));
    return false;
  }
  
  return true;
};

export default config;
