/**
 * Runtime Configuration for Consultant Portal
 * Loaded from /config.json at runtime (generated by CDK Custom Resource)
 */

export interface AppConfig {
  region: string;
  cognitoUserPoolId: string;
  cognitoClientId: string;
  cognitoDomain: string;
  cloudFrontUrl: string;
  apiEndpoint: string;
  demoMode: boolean;
  portalType: string;
}

// Default config (will be replaced by runtime config)
let _config: AppConfig = {
  region: 'ap-northeast-1',
  cognitoUserPoolId: '',
  cognitoClientId: '',
  cognitoDomain: '',
  cloudFrontUrl: '',
  apiEndpoint: '',
  demoMode: true,
  portalType: 'consultant'
};

export const config = _config;

export async function loadConfig(): Promise<void> {
  try {
    const response = await fetch('/config.json');
    if (response.ok) {
      const runtimeConfig = await response.json();
      Object.assign(_config, {
        region: runtimeConfig.region || _config.region,
        cognitoUserPoolId: runtimeConfig.cognitoUserPoolId || '',
        cognitoClientId: runtimeConfig.cognitoClientId || '',
        cognitoDomain: runtimeConfig.cognitoDomain || '',
        cloudFrontUrl: runtimeConfig.cloudFrontUrl || globalThis.location.origin,
        apiEndpoint: runtimeConfig.apiEndpoint || '',
        demoMode: !runtimeConfig.cognitoClientId,
        portalType: runtimeConfig.portalType || 'consultant'
      });
      console.log('Config loaded:', { ...config, cognitoClientId: '***' });
    } else {
      console.warn('Config not found, using demo mode');
    }
  } catch (error) {
    console.warn('Failed to load config, using demo mode:', error);
  }
}

export function validateConfig(): boolean {
  if (config.demoMode) return true;
  return !!(config.cognitoUserPoolId && config.cognitoClientId && config.cognitoDomain);
}
